// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetDetail(arg1:string):Promise<main.Xiaoshuo>;

export function Greet(arg1:main.XzInfo):Promise<string>;
